Multiple linear Regression

use scikit-learn to implement multiple linear regression
create, train & test a multiple linear model on real data

step1 - install and import required packages

In [ ]:
!pip install numpy==2.2.0
!pip install pandas==2.2.3
!pip install scikit-learn==1.6.0
!pip install matplotlib==3.9.3

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
url= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%202/data/FuelConsumptionCo2.csv"

Load the data

In [4]:
df = pd.read_csv(url)
df.head()

   MODELYEAR   MAKE  ... FUELCONSUMPTION_COMB_MPG CO2EMISSIONS
0       2014  ACURA  ...                       33          196
1       2014  ACURA  ...                       29          221
2       2014  ACURA  ...                       48          136
3       2014  ACURA  ...                       25          255
4       2014  ACURA  ...                       27          244

[5 rows x 13 columns]

In [5]:
df.describe()

       MODELYEAR   ENGINESIZE  ...  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
count     1067.0  1067.000000  ...               1067.000000   1067.000000
mean      2014.0     3.346298  ...                 26.441425    256.228679
std          0.0     1.415895  ...                  7.468702     63.372304
min       2014.0     1.000000  ...                 11.000000    108.000000
25%       2014.0     2.000000  ...                 21.000000    207.000000
50%       2014.0     3.400000  ...                 26.000000    251.000000
75%       2014.0     4.300000  ...                 31.000000    294.000000
max       2014.0     8.400000  ...                 60.000000    488.000000

[8 rows x 8 columns]

similar to linear model, drop the fields that are not required

In [6]:
df = df.drop(['MODELYEAR','MAKE','MODEL','VEHICLECLASS','TRANSMISSION','FUELTYPE'], axis=1)
df.head()

   ENGINESIZE  CYLINDERS  ...  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
0         2.0          4  ...                        33           196
1         2.4          4  ...                        29           221
2         1.5          4  ...                        48           136
3         3.5          6  ...                        25           255
4         3.5          6  ...                        27           244

[5 rows x 7 columns]

In [7]:
df.describe()

        ENGINESIZE    CYLINDERS  ...  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
count  1067.000000  1067.000000  ...               1067.000000   1067.000000
mean      3.346298     5.794752  ...                 26.441425    256.228679
std       1.415895     1.797447  ...                  7.468702     63.372304
min       1.000000     3.000000  ...                 11.000000    108.000000
25%       2.000000     4.000000  ...                 21.000000    207.000000
50%       3.400000     6.000000  ...                 26.000000    251.000000
75%       4.300000     8.000000  ...                 31.000000    294.000000
max       8.400000    12.000000  ...                 60.000000    488.000000

[8 rows x 7 columns]

In [10]:
df = df.drop(['CYLINDERS', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB',],axis=1)
df.head()

   ENGINESIZE  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
0         2.0                        33           196
1         2.4                        29           221
2         1.5                        48           136
3         3.5                        25           255
4         3.5                        27           244

In [11]:
df.describe()

        ENGINESIZE  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
count  1067.000000               1067.000000   1067.000000
mean      3.346298                 26.441425    256.228679
std       1.415895                  7.468702     63.372304
min       1.000000                 11.000000    108.000000
25%       2.000000                 21.000000    207.000000
50%       3.400000                 26.000000    251.000000
75%       4.300000                 31.000000    294.000000
max       8.400000                 60.000000    488.000000